{
 "title": "EMQX",
 "description": "Default EMQX 5.0 Grafana Monitoring Dashboard Template",
 "tags": [
  "EMQX",
  "MQTT"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  {
   "title": "Active Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(emqx_topics_count{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Active Topics"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "emqx_topics_count{instance=~\".*\",job=\"emqx\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_messages_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Messages Received"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_sent{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  {
   "title": "Messages Received Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_received{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  {
   "title": "Traffic Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_bytes_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_bytes_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_retained_count{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  {
   "title": "Messages Dropped Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_messages_dropped{instance=~\".*\",job=\"emqx\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\".*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{instance=~\".*\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\".*\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\".*\"} - node_boot_time_seconds{instance=~\".*\"}"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "EMQX Nodes running"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "EMQX Nodes stopped"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Erlang VM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(emqx_vm_used_memory{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "VM Memory Used"
    }
   ]
  },
  {
   "title": "Mnesia (built-in database) Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(erlang_mnesia_memory_usage_bytes{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Mnesia (built-in database) Memory Usage"
    }
   ]
  },
  {
   "title": "Erlang VM Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(erlang_vm_process_count{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Process Count"
    },
    {
     "expr": "sum(erlang_vm_statistics_run_queues_length_total{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Run Queue Length"
    }
   ]
  },
  {
   "title": "Erlang VM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(erlang_vm_threads{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(erlang_vm_thread_pool_size{instance=~\".*\",job=\"emqx\"})",
     "legendFormat": "Thread Pool size"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  },
  {
   "title": "Packets Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_connect{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_connect{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Connect"
    },
    {
     "expr": "sum(rate(emqx_packets_connack_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_connack_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Connack Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_connack_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_connack_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Connack Error"
    }
   ]
  },
  {
   "title": "Packets Disconnect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_disconnect_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_disconnect_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Disconnect Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_disconnect_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_disconnect_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Disconnect Received"
    }
   ]
  },
  {
   "title": "Packets Publish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_publish_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_publish_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Publish Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_publish_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Publish Received"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_dropped{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_publish_dropped{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Publish Dropped"
    },
    {
     "expr": "sum(rate(emqx_packets_publish_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_publish_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Publish Error"
    }
   ]
  },
  {
   "title": "Packets Subscribe/Unsubscribe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_subscribe_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_subscribe_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Subscribe Received"
    },
    {
     "expr": "sum(rate(emqx_packets_suback_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_suback_sent{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Suback Sent"
    },
    {
     "expr": "sum(rate(emqx_packets_subscribe_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_subscribe_error{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Subscribe Error"
    },
    {
     "expr": "sum(rate(emqx_packets_unsubscribe_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]) or irate(emqx_packets_unsubscribe_received{instance=~\".*\",job=\"emqx\"}[$__rate_interval]))",
     "legendFormat": "Packets Unsubscribe Received"
    },
    {
     "expr": "sum(rate(emqx_packets_unsubscribe_error{instance=~\".*\",job=\"emqx\"}[$__interval]) or irate(emqx_packets_unsubscribe_error{instance=~\".*\",job=\"emqx\"}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Error"
    }
   ]
  }
 ]
}